// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.Db;

#nullable disable

namespace TicketingSystem.Db.Migrations
{
    [DbContext(typeof(TicketingSystemDbContext))]
    partial class TicketingSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("TicketingSystem.Db.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsITTeam")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsITTeam");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK__AppUsers__3214EC07FA8831BC");

                    b.HasIndex(new[] { "Email" }, "IX_AppUsers_Email")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "testacc@co.nz",
                            FullName = "Test User",
                            IsActive = false,
                            IsITTeam = false,
                            PasswordHash = "Admin@123"
                        });
                });

            modelBuilder.Entity("TicketingSystem.Db.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnResolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmittedByDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Urgency")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK__Ticket__3214EC07216C54FD");

                    b.HasIndex(new[] { "AssignedToUserId" }, "IX_Ticket_AssignedToUserId");

                    b.HasIndex(new[] { "Status" }, "IX_Ticket_Status");

                    b.HasIndex(new[] { "SubmittedByUserId" }, "IX_Ticket_SubmittedByUserId");

                    b.ToTable("Ticket", null, t =>
                        {
                            t.HasTrigger("trg_Ticket_NewTicketEmail");
                        });
                });

            modelBuilder.Entity("TicketingSystem.Db.Models.Ticket", b =>
                {
                    b.HasOne("TicketingSystem.Db.Models.AppUser", "AssignedToUser")
                        .WithMany("TicketAssignedToUsers")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Ticket_AssignedTo");

                    b.HasOne("TicketingSystem.Db.Models.AppUser", "SubmittedByUser")
                        .WithMany("TicketSubmittedByUsers")
                        .HasForeignKey("SubmittedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_SubmittedBy");

                    b.Navigation("AssignedToUser");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("TicketingSystem.Db.Models.AppUser", b =>
                {
                    b.Navigation("TicketAssignedToUsers");

                    b.Navigation("TicketSubmittedByUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
